name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      
      - name: Install jest seperatly
        run: npm install jest --force
        
      - name: Install enzyme 
        run: npm install enzyme --force

      - name: Test
        run: npm test
