# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" , "develop", "smart_ci" ]
  pull_request:
    branches: [ "main" , "develop", "smart_ci" ]

jobs:
  build:
    defaults:
       run:
         working-directory: ./maltebon/

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install @babel/preset-react
    - run: npm install @babel/preset-env
    - run: npm install @babel/plugin-transform-modules-commonjs
    - run: npm install -g jest
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --updateSnapshot
